/* Generated by the Deck Editor (or its Export button) — a full replacement
   card list for WOA_BUILTIN.cards, applied before the engine loads. null =
   use the built-in deck from maps.js. Loaded in browsers only; node tools
   (test.js, balance.js) always read maps.js. */
window.WOA_CUSTOM_DECK = null;
