/* Generated by the Deck Editor — the APPLIED deck (a full card list), or null.
   Loaded before engine.js; it overrides the active content deck
   (content/decks/default.js) as WOA_CONTENT's active deck. null = use the
   default deck. Browser-only; node tools read content/decks/*.js. */
window.WOA_CUSTOM_DECK = null;
