/* War of Attrition — tiny zero-dependency LAN + dev server.
   Run:  node server.js   (or double-click run-server.command / run-server.bat)
   Then open the printed address on both devices (same wifi).

   Also the browser's write proxy: content saves (maps/decks), report/debug
   saves, and — V1 — per-battle persistence into logs/woa.db via dev/db.js.
   The db require is guarded: a zipped game/ without dev/ still serves and
   plays; /api/recordbattle just answers 501. */
'use strict';
var http = require('http');
var fs = require('fs');
var path = require('path');
var os = require('os');

var PORT = process.env.PORT || 8420;
var ROOT = __dirname;
var MIME = { '.html': 'text/html', '.js': 'text/javascript', '.css': 'text/css', '.png': 'image/png', '.jpg': 'image/jpeg', '.svg': 'image/svg+xml', '.ico': 'image/x-icon', '.json': 'application/json', '.md': 'text/markdown' };

// --- content files (Feedback Round 4 Pass 2): maps/decks are per-item files
// under content/, each registering into WOA_CONTENT; content/manifest.js is
// regenerated (by scanning the dirs) so the browser loads exactly what's there.
var CONTENT_DIR = path.join(ROOT, 'content');
var CONTENT_KINDS = (function () {
  try { return require(path.join(CONTENT_DIR, 'kinds.js')); } catch (e) { return ['decks', 'maps', 'mapsets']; }
})();
function contentSlug(s) { return String(s || 'map').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') || 'map'; }
function wrapContent(kind, obj) {
  // defensive: files written before a kind existed init WOA_CONTENT without it,
  // so every file ensures its own array rather than trusting the initializer
  return "(function(g){var c=g.WOA_CONTENT=g.WOA_CONTENT||{maps:[],cards:[],decks:[],mapsets:[]};(c." + kind + "=c." + kind + "||[]).push(\n" +
    JSON.stringify(obj, null, 1) + "\n);})(typeof window!=='undefined'?window:globalThis);\n";
}
function regenContentManifest() {
  function list(kind) { try { return fs.readdirSync(path.join(CONTENT_DIR, kind)).filter(function (f) { return /\.js$/.test(f); }).sort(); } catch (e) { return []; } }
  var files = {};
  CONTENT_KINDS.forEach(function (k) { files[k] = list(k); });
  var body =
    "/* GENERATED by the server — the browser content loader (document.write()s\n" +
    "   content files into WOA_CONTENT before the engine runs). */\n" +
    "(function (g) {\n" +
    "  var files = " + JSON.stringify(files) + ";\n" +
    "  g.WOA_CONTENT_MANIFEST = files;\n" +
    "  if (typeof document !== 'undefined' && document.write) {\n" +
    "    " + JSON.stringify(CONTENT_KINDS) + ".forEach(function (kind) {\n" +
    "      files[kind].forEach(function (f) { document.write('<script src=\"content/' + kind + '/' + f + '\"><\\/script>'); });\n" +
    "    });\n" +
    "  }\n" +
    "})(typeof window !== 'undefined' ? window : globalThis);\n";
  fs.writeFileSync(path.join(CONTENT_DIR, 'manifest.js'), body);
}
// Regenerate at boot too, not just on save/delete — hand-added content files
// (or a git pull) otherwise leave the browser on a stale roster.
try { regenContentManifest(); } catch (e) { console.log('  (manifest regen failed: ' + e.message + ')'); }

// --- V1 battle persistence (guarded: dev/ may be absent from a zip) ---------
var db = null, dbHandle = null, dbRuns = {}; // runKey -> runId (per server boot)
try { db = require(path.join(ROOT, '..', 'dev', 'db.js')); } catch (e) { /* persistence off */ }
function recordBattle(body) {
  if (!db) return { status: 501, out: { error: 'persistence unavailable (dev/db.js not present)' } };
  if (!body || !body.state || body.state.phase !== 'battle-over' || !body.run)
    return { status: 400, out: { error: 'need a finished state + run info' } };
  if (!dbHandle) dbHandle = db.open();
  var runKey = String(body.runKey || (body.run.kind + '|' + (body.run.version || '?') + '|' + (body.run.redAi || '?') + '|' + (body.run.blueAi || '?')));
  if (!dbRuns[runKey]) dbRuns[runKey] = db.insertRun(dbHandle, body.run);
  var battleId = db.insertBattle(dbHandle, dbRuns[runKey], body.state, body.firstPlayer || 'red',
    { seed: body.seed, version: body.run.version });
  return { status: 200, out: { ok: true, runId: dbRuns[runKey], battleId: battleId } };
}

var VERSION = (function () { // engine's rules version, for LAN mismatch warnings
  try { return require(path.join(ROOT, 'engine.js')).VERSION; } catch (e) { return null; }
})();

var rooms = {}; // code -> { state, seq, updated }

function code4() {
  var letters = 'ABCDEFGHJKMNPQRSTUVWXYZ'; // no I/L/O
  var c = '';
  for (var i = 0; i < 4; i++) c += letters[Math.floor(Math.random() * letters.length)];
  return rooms[c] ? code4() : c;
}

function stamp() { return new Date().toTimeString().slice(0, 8); }
function logRooms(msg) {
  var open = Object.keys(rooms).sort().join(' ') || 'none';
  console.log('  [' + stamp() + '] ' + msg + '   (open rooms: ' + open + ')');
}

function cleanup() {
  var now = Date.now();
  for (var c in rooms) {
    if (now - rooms[c].updated > 6 * 3600 * 1000) {
      delete rooms[c];
      logRooms('room ' + c + ' expired after 6h idle');
    }
  }
}
setInterval(cleanup, 600000);

function json(res, status, obj) {
  var body = JSON.stringify(obj);
  res.writeHead(status, { 'Content-Type': 'application/json', 'Cache-Control': 'no-store' });
  res.end(body);
}

function readBody(req, cb) {
  var chunks = [];
  var size = 0;
  req.on('data', function (d) {
    size += d.length;
    if (size > 2e6) { req.destroy(); return; }
    chunks.push(d);
  });
  req.on('end', function () {
    try { cb(null, JSON.parse(Buffer.concat(chunks).toString('utf8') || '{}')); }
    catch (e) { cb(e); }
  });
}

// One "save a file under a whitelisted repo dir" helper — the shared shape of
// savereport/savedebug (filename + version regexes are the path-injection fence).
function saveUnderRepo(res, relDirParts, name, nameRe, content) {
  if (!nameRe.test(name)) return json(res, 400, { error: 'bad filename' });
  var rel = path.join.apply(path, relDirParts);
  var dir = path.join(ROOT, '..', rel);
  fs.mkdir(dir, { recursive: true }, function (merr) {
    if (merr) return json(res, 500, { error: 'mkdir failed' });
    fs.writeFile(path.join(dir, name), content, function (werr) {
      if (werr) return json(res, 500, { error: 'write failed' });
      json(res, 200, { ok: true, path: rel + '/' + name });
    });
  });
}

/* ---- the API, one route per row ------------------------------------------ */
var ROUTES = {
  'POST /api/create': function (req, res, body) {
    if (!body.state) return json(res, 400, { error: 'bad request' });
    var room = code4();
    rooms[room] = { state: body.state, seq: 1, updated: Date.now() };
    logRooms('room ' + room + ' hosted by ' + (req.socket.remoteAddress || '?'));
    json(res, 200, { room: room, seq: 1, version: VERSION });
  },
  'POST /api/join': function (req, res, body) {
    var r = rooms[(body.room || '').toUpperCase()];
    if (!r) return json(res, 404, { error: 'room not found' });
    r.updated = Date.now();
    logRooms('room ' + (body.room || '').toUpperCase() + ' joined by ' + (req.socket.remoteAddress || '?'));
    json(res, 200, { state: r.state, seq: r.seq, version: VERSION });
  },
  'POST /api/push': function (req, res, body) {
    var r = rooms[(body.room || '').toUpperCase()];
    if (!r) return json(res, 404, { error: 'room not found' });
    r.updated = Date.now();
    if (body.seq !== r.seq + 1) return json(res, 200, { conflict: true, state: r.state, seq: r.seq });
    r.seq = body.seq;
    r.state = body.state;
    json(res, 200, { ok: true, seq: r.seq });
  },
  'POST /api/savemap': function (req, res, body) {
    // write one map to content/maps/<id>.js and refresh the manifest
    var m = body.map;
    if (!m || !m.name) return json(res, 400, { error: 'bad request' });
    var id = contentSlug(m.id || m.name); m.id = id;
    var dir = path.join(CONTENT_DIR, 'maps');
    fs.mkdir(dir, { recursive: true }, function (merr) {
      if (merr) return json(res, 500, { error: 'mkdir failed' });
      fs.writeFile(path.join(dir, id + '.js'), wrapContent('maps', m), function (werr) {
        if (werr) return json(res, 500, { error: 'write failed' });
        try { regenContentManifest(); } catch (e) {}
        json(res, 200, { ok: true, path: 'content/maps/' + id + '.js' });
      });
    });
  },
  'POST /api/deletemap': function (req, res, body) {
    // delete content/maps/<id>.js (id is slug-sanitized — no path escape) + refresh
    if (!body.id) return json(res, 400, { error: 'bad request' });
    var id = contentSlug(body.id);
    fs.unlink(path.join(CONTENT_DIR, 'maps', id + '.js'), function () {
      try { regenContentManifest(); } catch (e) {}      // ENOENT is fine — already gone
      json(res, 200, { ok: true, deleted: 'content/maps/' + id + '.js' });
    });
  },
  'POST /api/savedeck': function (req, res, body) {
    // the Deck Editor's applied-deck file: deck = card list, or null to fall
    // back to the default deck (content/decks/default.js)
    if (!('deck' in body)) return json(res, 400, { error: 'bad request' });
    var content = 'window.WOA_CUSTOM_DECK = ' + JSON.stringify(body.deck, null, 1) + ';\n';
    fs.writeFile(path.join(ROOT, 'custom-deck.js'), content, function (werr) {
      if (werr) return json(res, 500, { error: 'write failed' });
      json(res, 200, { ok: true });
    });
  },
  'POST /api/savereport': function (req, res, body) {
    // Balance Dashboard report -> logs/reports/balance/<version>/ (Round 4)
    if (!body.filename || typeof body.content !== 'string') return json(res, 400, { error: 'bad request' });
    var ver = String(body.version || '0.0');
    if (!/^[A-Za-z0-9._-]+$/.test(ver)) return json(res, 400, { error: 'bad version' });
    saveUnderRepo(res, ['logs', 'reports', 'balance', ver], String(body.filename), /^[A-Za-z0-9._-]+\.md$/, body.content);
  },
  'POST /api/savedebug': function (req, res, body) {
    // game-state snapshot -> logs/debug/ so Bill can point Claude at an exact
    // situation instead of pasting a screenshot (Round 4)
    if (!body.filename || typeof body.content !== 'string') return json(res, 400, { error: 'bad request' });
    saveUnderRepo(res, ['logs', 'debug'], String(body.filename), /^[A-Za-z0-9._-]+\.json$/, body.content);
  },
  'POST /api/savemapsets': function (req, res, body) {
    // The Map-Sets panel owns the full slot state (like the deck slots): it
    // POSTs every named set + which one is active; we rewrite the whole
    // content/mapsets/ dir to match (files not in the list are deleted).
    var sets = body.mapsets;
    if (!Array.isArray(sets) || sets.length > 8) return json(res, 400, { error: 'bad request' });
    var dir = path.join(CONTENT_DIR, 'mapsets');
    try {
      fs.mkdirSync(dir, { recursive: true });
      var keep = {};
      sets.forEach(function (m) {
        if (!m || !m.name || !Array.isArray(m.maps)) throw new Error('bad mapset');
        var id = contentSlug(m.id || m.name);
        keep[id + '.js'] = true;
        fs.writeFileSync(path.join(dir, id + '.js'),
          wrapContent('mapsets', { id: id, name: String(m.name), active: !!m.active, maps: m.maps.map(String) }));
      });
      fs.readdirSync(dir).filter(function (f) { return /\.js$/.test(f) && !keep[f]; })
        .forEach(function (f) { fs.unlinkSync(path.join(dir, f)); });
      regenContentManifest();
      json(res, 200, { ok: true, files: Object.keys(keep) });
    } catch (e) { json(res, 500, { error: e.message }); }
  },
  'POST /api/recordbattle': function (req, res, body) {
    // V1: one finished battle -> a per-battle row in logs/woa.db.
    // body = { run:{version,kind,redAi,blueAi,n,tool,notes,deck,mapset,seedBase,label,baseline},
    //   runKey?, state, firstPlayer, seed } — run is forwarded to db.insertRun as-is
    // (WOA-032, SPEC §7: run identity); the caller (the dashboard Run loop) stamps
    // deck/mapset/seedBase, never this proxy — the server stays a dumb pass-through.
    try {
      var r = recordBattle(body);
      json(res, r.status, r.out);
    } catch (e) { json(res, 500, { error: e.message }); }
  },
  'GET /api/poll': function (req, res, body, u) {
    var r = rooms[(u.searchParams.get('room') || '').toUpperCase()];
    if (!r) return json(res, 404, { error: 'room not found' });
    r.updated = Date.now();
    var seq = parseInt(u.searchParams.get('seq') || '0', 10);
    if (r.seq > seq) return json(res, 200, { state: r.state, seq: r.seq });
    res.writeHead(204); return res.end();
  }
};

http.createServer(function (req, res) {
  var u = new URL(req.url, 'http://x');
  var route = ROUTES[req.method + ' ' + u.pathname];
  if (route) {
    if (req.method === 'GET') return route(req, res, null, u);
    return readBody(req, function (err, body) {
      if (err || !body) return json(res, 400, { error: 'bad request' });
      route(req, res, body, u);
    });
  }

  /* ---- static files ---- */
  var file = u.pathname === '/' ? '/index.html' : u.pathname;
  file = path.normalize(file).replace(/^(\.\.[\/\\])+/, '');
  var full = path.join(ROOT, file);
  if (!full.startsWith(ROOT)) { res.writeHead(403); return res.end(); }
  fs.readFile(full, function (err, data) {
    if (err) { res.writeHead(404); return res.end('not found'); }
    res.writeHead(200, { 'Content-Type': MIME[path.extname(full)] || 'application/octet-stream', 'Cache-Control': 'no-store' });
    res.end(data);
  });
}).on('error', function (err) {
  if (err.code === 'EADDRINUSE') {
    console.log('');
    console.log('  Port ' + PORT + ' is already taken — the server is probably already running');
    console.log('  in another window (check http://localhost:' + PORT + '). Close that window,');
    console.log('  or run with a different port:  PORT=8421 node server.js   (Windows: set PORT=8421 && node server.js)');
    process.exit(1);
  }
  throw err;
}).listen(PORT, function () {
  console.log('');
  console.log('  WAR OF ATTRITION — server running' + (VERSION ? '   (rules ' + VERSION + ')' : ''));
  console.log('  ---------------------------------');
  console.log('  On this computer:  http://localhost:' + PORT);
  var ifaces = os.networkInterfaces();
  Object.keys(ifaces).forEach(function (name) {
    (ifaces[name] || []).forEach(function (i) {
      if (i.family === 'IPv4' && !i.internal) {
        console.log('  Other devices:     http://' + i.address + ':' + PORT + '   (same wifi)');
      }
    });
  });
  console.log('  Battle persistence: ' + (db ? 'ON -> logs/woa.db' : 'off (dev/db.js not found — fine for a zipped copy)'));
  console.log('');
  console.log('  One player clicks "Host a Room", the other enters the 4-letter code.');
  console.log('  Press Ctrl+C to stop.');
});
