/* War of Attrition — tiny zero-dependency LAN server.
   Run:  node server.js   (or double-click run-server.bat on Windows)
   Then open the printed address on both devices (same wifi). */
'use strict';
var http = require('http');
var fs = require('fs');
var path = require('path');
var os = require('os');

var PORT = process.env.PORT || 8420;
var ROOT = __dirname;
var MIME = { '.html': 'text/html', '.js': 'text/javascript', '.css': 'text/css', '.png': 'image/png', '.jpg': 'image/jpeg', '.svg': 'image/svg+xml', '.ico': 'image/x-icon' };

// --- content files (Feedback Round 4 Pass 2): maps/decks are per-item files
// under content/, each registering into WOA_CONTENT; content/manifest.js is
// regenerated (by scanning the dirs) so the browser loads exactly what's there.
var CONTENT_DIR = path.join(ROOT, 'content');
function contentSlug(s) { return String(s || 'map').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') || 'map'; }
function wrapContent(kind, obj) {
  return "(function(g){(g.WOA_CONTENT=g.WOA_CONTENT||{maps:[],cards:[],decks:[]})." + kind + ".push(\n" +
    JSON.stringify(obj, null, 1) + "\n);})(typeof window!=='undefined'?window:globalThis);\n";
}
function regenContentManifest() {
  function list(kind) { try { return fs.readdirSync(path.join(CONTENT_DIR, kind)).filter(function (f) { return /\.js$/.test(f); }).sort(); } catch (e) { return []; } }
  var body =
    "/* GENERATED by the server — the browser content loader (document.write()s\n" +
    "   content/decks/*.js + content/maps/*.js into WOA_CONTENT before engine.js). */\n" +
    "(function (g) {\n" +
    "  var files = { decks: " + JSON.stringify(list('decks')) + ", maps: " + JSON.stringify(list('maps')) + " };\n" +
    "  g.WOA_CONTENT_MANIFEST = files;\n" +
    "  if (typeof document !== 'undefined' && document.write) {\n" +
    "    ['decks', 'maps'].forEach(function (kind) {\n" +
    "      files[kind].forEach(function (f) { document.write('<script src=\"content/' + kind + '/' + f + '\"><\\/script>'); });\n" +
    "    });\n" +
    "  }\n" +
    "})(typeof window !== 'undefined' ? window : globalThis);\n";
  fs.writeFileSync(path.join(CONTENT_DIR, 'manifest.js'), body);
}

// Regenerate the manifest at boot too, not just on save/delete — hand-added
// content files (or a git pull) otherwise leave the browser on a stale roster
// while node tools see the truth.
try { regenContentManifest(); } catch (e) { console.log('  (manifest regen failed: ' + e.message + ')'); }

var rooms = {}; // code -> { state, seq, updated }

function code4() {
  var letters = 'ABCDEFGHJKMNPQRSTUVWXYZ'; // no I/L/O
  var c = '';
  for (var i = 0; i < 4; i++) c += letters[Math.floor(Math.random() * letters.length)];
  return rooms[c] ? code4() : c;
}

function stamp() { return new Date().toTimeString().slice(0, 8); }
function logRooms(msg) {
  var open = Object.keys(rooms).sort().join(' ') || 'none';
  console.log('  [' + stamp() + '] ' + msg + '   (open rooms: ' + open + ')');
}

function cleanup() {
  var now = Date.now();
  for (var c in rooms) {
    if (now - rooms[c].updated > 6 * 3600 * 1000) {
      delete rooms[c];
      logRooms('room ' + c + ' expired after 6h idle');
    }
  }
}
setInterval(cleanup, 600000);

function json(res, status, obj) {
  var body = JSON.stringify(obj);
  res.writeHead(status, { 'Content-Type': 'application/json', 'Cache-Control': 'no-store' });
  res.end(body);
}

function readBody(req, cb) {
  var chunks = [];
  var size = 0;
  req.on('data', function (d) {
    size += d.length;
    if (size > 2e6) { req.destroy(); return; }
    chunks.push(d);
  });
  req.on('end', function () {
    try { cb(null, JSON.parse(Buffer.concat(chunks).toString('utf8') || '{}')); }
    catch (e) { cb(e); }
  });
}

http.createServer(function (req, res) {
  var u = new URL(req.url, 'http://x');
  var p = u.pathname;

  /* ---- API ---- */
  if (p === '/api/create' && req.method === 'POST') {
    return readBody(req, function (err, body) {
      if (err || !body.state) return json(res, 400, { error: 'bad request' });
      var room = code4();
      rooms[room] = { state: body.state, seq: 1, updated: Date.now() };
      logRooms('room ' + room + ' hosted by ' + (req.socket.remoteAddress || '?'));
      json(res, 200, { room: room, seq: 1 });
    });
  }
  if (p === '/api/join' && req.method === 'POST') {
    return readBody(req, function (err, body) {
      var r = body && rooms[(body.room || '').toUpperCase()];
      if (err || !r) return json(res, 404, { error: 'room not found' });
      r.updated = Date.now();
      logRooms('room ' + (body.room || '').toUpperCase() + ' joined by ' + (req.socket.remoteAddress || '?'));
      json(res, 200, { state: r.state, seq: r.seq });
    });
  }
  if (p === '/api/push' && req.method === 'POST') {
    return readBody(req, function (err, body) {
      var r = body && rooms[(body.room || '').toUpperCase()];
      if (err || !r) return json(res, 404, { error: 'room not found' });
      r.updated = Date.now();
      if (body.seq !== r.seq + 1) return json(res, 200, { conflict: true, state: r.state, seq: r.seq });
      r.seq = body.seq;
      r.state = body.state;
      json(res, 200, { ok: true, seq: r.seq });
    });
  }
  if (p === '/api/savemap' && req.method === 'POST') {
    // write one map to content/maps/<id>.js and refresh the manifest
    return readBody(req, function (err, body) {
      var m = body && body.map;
      if (err || !m || !m.name) return json(res, 400, { error: 'bad request' });
      var id = contentSlug(m.id || m.name); m.id = id;
      var dir = path.join(CONTENT_DIR, 'maps');
      fs.mkdir(dir, { recursive: true }, function (merr) {
        if (merr) return json(res, 500, { error: 'mkdir failed' });
        fs.writeFile(path.join(dir, id + '.js'), wrapContent('maps', m), function (werr) {
          if (werr) return json(res, 500, { error: 'write failed' });
          try { regenContentManifest(); } catch (e) {}
          json(res, 200, { ok: true, path: 'content/maps/' + id + '.js' });
        });
      });
    });
  }
  if (p === '/api/deletemap' && req.method === 'POST') {
    // delete content/maps/<id>.js (id is slug-sanitized — no path escape) + refresh
    return readBody(req, function (err, body) {
      if (err || !body || !body.id) return json(res, 400, { error: 'bad request' });
      var id = contentSlug(body.id);
      fs.unlink(path.join(CONTENT_DIR, 'maps', id + '.js'), function () {
        try { regenContentManifest(); } catch (e) {}      // ENOENT is fine — already gone
        json(res, 200, { ok: true, deleted: 'content/maps/' + id + '.js' });
      });
    });
  }
  if (p === '/api/savedeck' && req.method === 'POST') {
    // the Deck Editor's applied-deck file: deck = card list, or null to fall
    // back to the default deck (content/decks/default.js)
    return readBody(req, function (err, body) {
      if (err || !('deck' in body)) return json(res, 400, { error: 'bad request' });
      var content = 'window.WOA_CUSTOM_DECK = ' + JSON.stringify(body.deck, null, 1) + ';\n';
      fs.writeFile(path.join(ROOT, 'custom-deck.js'), content, function (werr) {
        if (werr) return json(res, 500, { error: 'write failed' });
        json(res, 200, { ok: true });
      });
    });
  }
  if (p === '/api/savereport' && req.method === 'POST') {
    // Save a Balance Dashboard report to logs/reports/balance/<version>/ so Bill,
    // Claude and the report skills all read the same numbers (Feedback Round 4).
    // filename + version are validated (no path escape).
    return readBody(req, function (err, body) {
      if (err || !body.filename || typeof body.content !== 'string') return json(res, 400, { error: 'bad request' });
      var name = String(body.filename);
      if (!/^[A-Za-z0-9._-]+\.md$/.test(name)) return json(res, 400, { error: 'bad filename' });
      var ver = String(body.version || '0.0');
      if (!/^[A-Za-z0-9._-]+$/.test(ver)) return json(res, 400, { error: 'bad version' });
      var rel = path.join('logs', 'reports', 'balance', ver);
      var dir = path.join(ROOT, '..', rel);
      fs.mkdir(dir, { recursive: true }, function (merr) {
        if (merr) return json(res, 500, { error: 'mkdir failed' });
        fs.writeFile(path.join(dir, name), body.content, function (werr) {
          if (werr) return json(res, 500, { error: 'write failed' });
          json(res, 200, { ok: true, path: rel + '/' + name });
        });
      });
    });
  }
  if (p === '/api/savedebug' && req.method === 'POST') {
    // Save a game-state snapshot to logs/debug/ so Bill can point Claude at an
    // exact situation instead of pasting a screenshot (Feedback Round 4).
    return readBody(req, function (err, body) {
      if (err || !body.filename || typeof body.content !== 'string') return json(res, 400, { error: 'bad request' });
      var name = String(body.filename);
      if (!/^[A-Za-z0-9._-]+\.json$/.test(name)) return json(res, 400, { error: 'bad filename' });
      var rel = path.join('logs', 'debug');
      var dir = path.join(ROOT, '..', rel);
      fs.mkdir(dir, { recursive: true }, function (merr) {
        if (merr) return json(res, 500, { error: 'mkdir failed' });
        fs.writeFile(path.join(dir, name), body.content, function (werr) {
          if (werr) return json(res, 500, { error: 'write failed' });
          json(res, 200, { ok: true, path: rel + '/' + name });
        });
      });
    });
  }
  if (p === '/api/poll' && req.method === 'GET') {
    var r = rooms[(u.searchParams.get('room') || '').toUpperCase()];
    if (!r) return json(res, 404, { error: 'room not found' });
    r.updated = Date.now();
    var seq = parseInt(u.searchParams.get('seq') || '0', 10);
    if (r.seq > seq) return json(res, 200, { state: r.state, seq: r.seq });
    res.writeHead(204); return res.end();
  }

  /* ---- static files ---- */
  var file = p === '/' ? '/index.html' : p;
  file = path.normalize(file).replace(/^(\.\.[\/\\])+/, '');
  var full = path.join(ROOT, file);
  if (!full.startsWith(ROOT)) { res.writeHead(403); return res.end(); }
  fs.readFile(full, function (err, data) {
    if (err) { res.writeHead(404); return res.end('not found'); }
    res.writeHead(200, { 'Content-Type': MIME[path.extname(full)] || 'application/octet-stream', 'Cache-Control': 'no-store' });
    res.end(data);
  });
}).on('error', function (err) {
  if (err.code === 'EADDRINUSE') {
    console.log('');
    console.log('  Port ' + PORT + ' is already taken — the server is probably already running');
    console.log('  in another window (check http://localhost:' + PORT + '). Close that window,');
    console.log('  or run with a different port:  set PORT=8421 && node server.js');
    process.exit(1);
  }
  throw err;
}).listen(PORT, function () {
  console.log('');
  console.log('  WAR OF ATTRITION — server running');
  console.log('  ---------------------------------');
  console.log('  On this computer:  http://localhost:' + PORT);
  var ifaces = os.networkInterfaces();
  Object.keys(ifaces).forEach(function (name) {
    (ifaces[name] || []).forEach(function (i) {
      if (i.family === 'IPv4' && !i.internal) {
        console.log('  Other devices:     http://' + i.address + ':' + PORT + '   (same wifi)');
      }
    });
  });
  console.log('');
  console.log('  One player clicks "Host a Room", the other enters the 4-letter code.');
  console.log('  Press Ctrl+C to stop.');
});
