/* Single source for the generated content/manifest.js body — required by
   game/server.js (which writes it) and game/test.js (which checks the
   committed file hasn't drifted). Node-only; no second copy of the
   file-listing logic. */
'use strict';
var fs = require('fs');
var path = require('path');
var CONTENT_DIR = __dirname;
var CONTENT_KINDS = require(path.join(CONTENT_DIR, 'kinds.js')); // single source; sits beside this file
function buildManifest() {
  function list(kind) { try { return fs.readdirSync(path.join(CONTENT_DIR, kind)).filter(function (f) { return /\.js$/.test(f); }).sort(); } catch (e) { return []; } }
  var files = {};
  CONTENT_KINDS.forEach(function (k) { files[k] = list(k); });
  return "/* GENERATED by the server — the browser content loader (document.write()s\n" +
    "   content files into WOA_CONTENT before the engine runs). */\n" +
    "(function (g) {\n" +
    "  var files = " + JSON.stringify(files) + ";\n" +
    "  g.WOA_CONTENT_MANIFEST = files;\n" +
    "  if (typeof document !== 'undefined' && document.write) {\n" +
    "    " + JSON.stringify(CONTENT_KINDS) + ".forEach(function (kind) {\n" +
    "      files[kind].forEach(function (f) { document.write('<script src=\"content/' + kind + '/' + f + '\"><\\/script>'); });\n" +
    "    });\n" +
    "  }\n" +
    "})(typeof window !== 'undefined' ? window : globalThis);\n";
}
function regen() { fs.writeFileSync(path.join(CONTENT_DIR, 'manifest.js'), buildManifest()); }
module.exports = { buildManifest: buildManifest, regen: regen, MANIFEST_PATH: path.join(CONTENT_DIR, 'manifest.js') };
