/* GENERATED by the server — the browser content loader (document.write()s
   content files into WOA_CONTENT before the engine runs). */
(function (g) {
  var files = {"decks":["default.js"],"maps":["causeway.js","frontier.js","killing-ground.js","long-march.js","riverbend.js","saber-ridge.js","the-cockpit.js","the-ford.js","the-marshes.js","the-narrows.js","the-void.js","twin-gates.js"],"mapsets":["rivers.js","tournament.js"]};
  g.WOA_CONTENT_MANIFEST = files;
  if (typeof document !== 'undefined' && document.write) {
    ["decks","maps","mapsets"].forEach(function (kind) {
      files[kind].forEach(function (f) { document.write('<script src="content/' + kind + '/' + f + '"><\/script>'); });
    });
  }
})(typeof window !== 'undefined' ? window : globalThis);
