/* GENERATED by the server — the browser content loader (document.write()s
   content files into WOA_CONTENT before the engine runs). */
(function (g) {
  var files = {"cards":["airdrop.js","attack_plus1.js","careful_maneuvers.js","clear_the_way.js","conscription.js","creeping_barrage.js","deep_strike.js","deploy_artillery.js","deploy_cav_single.js","deploy_cavalry.js","deploy_inf_start.js","deploy_inf_trench.js","forced_march.js","hold_the_line.js","mass_assault.js","naval_barrage.js","ordered_withdraw.js","over_the_top.js","raiding_party.js","reckless_maneuvers.js","sappers.js","shock_troops.js","storm_and_hold.js","vanguard.js"],"decks":["bestof.js","cavsplit-16.js","cavsplit-17.js","cavsplit17-raid-paid.js","cavsplit17-raid.js","cavsplit17-tempo.js","default.js","iter2.js","iter3.js"],"maps":["causeway.js","frontier.js","killing-ground.js","long-march.js","riverbend.js","saber-ridge.js","the-cauldron.js","the-clearing.js","the-cockpit.js","the-col.js","the-ford.js","the-marshes.js","the-narrows.js","the-salient.js","the-sluice.js","the-void.js","the-weir.js","twin-gates.js"],"mapsets":["bestof.js","core7.js","iter2.js","iter3.js","rivers.js","tournament.js"],"units":["shock-army.js"],"commanders":["forestier.js","woods-baiter.js"]};
  g.WOA_CONTENT_MANIFEST = files;
  if (typeof document !== 'undefined' && document.write) {
    ["cards","decks","maps","mapsets","units","commanders"].forEach(function (kind) {
      files[kind].forEach(function (f) { document.write('<script src="content/' + kind + '/' + f + '"><\/script>'); });
    });
  }
})(typeof window !== 'undefined' ? window : globalThis);
